name: Deploy Backend (placeholder)
on:
  push:
    branches: [ main ]
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Use Railway to connect this repo and configure automatic deploys."
